# Generated by Django 5.1.4 on 2026-07-09 00:54

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(db_index=True, help_text='CPF de 11 dígitos ou hash de CPF para integrações', max_length=64, unique=True, validators=[apps.core.models.validate_cpf]),
        ),
    ]
