# Generated by Django 5.1.4 on 2026-07-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeolocalizacaoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(db_index=True, help_text='CEP com 8 dígitos, sem formatação', max_length=10, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude no formato decimal', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude no formato decimal', max_digits=9, null=True)),
                ('cidade', models.CharField(blank=True, help_text='Cidade correspondente ao CEP', max_length=100)),
                ('estado', models.CharField(blank=True, help_text='Sigla do estado (ex: SP)', max_length=2)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da última atualização deste cache')),
            ],
            options={
                'verbose_name': 'Geolocalização Cache',
                'verbose_name_plural': 'Geolocalizações Cache',
                'ordering': ['-ultima_atualizacao'],
                'indexes': [models.Index(fields=['cep'], name='idx_geolocalizacao_cep')],
            },
        ),
    ]
