# Generated by Django 5.1.4 on 2026-07-21 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_geolocalizacaocache'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoUsuarioBarbearia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('DONO', 'Dono'), ('BARBEIRO', 'Barbeiro'), ('GERENTE', 'Gerente')], default='DONO', max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_usuario', to='tenants.barbearia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_barbearia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo Usuário-Barbearia',
                'verbose_name_plural': 'Vínculos Usuário-Barbearia',
                'indexes': [models.Index(fields=['usuario', 'papel'], name='core_vincul_usuario_9987e8_idx')],
                'unique_together': {('usuario', 'barbearia')},
            },
        ),
    ]
