# Generated by Django 5.1.4 on 2026-07-09 22:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbearia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da barbearia (tenant_id)', primary_key=True, serialize=False)),
                ('nome_comercial', models.CharField(help_text='Nome comercial da barbearia', max_length=255)),
                ('cnpj', models.CharField(db_index=True, help_text='CNPJ da barbearia (apenas 14 números)', max_length=14, unique=True)),
                ('cep', models.CharField(help_text='CEP da barbearia (apenas 8 números)', max_length=8)),
                ('logradouro', models.CharField(help_text='Endereço completo da barbearia', max_length=255)),
                ('numero', models.CharField(help_text='Número do endereço', max_length=10)),
                ('complemento', models.CharField(blank=True, help_text='Complemento do endereço (sala, andar, etc.)', max_length=100, null=True)),
                ('bairro', models.CharField(help_text='Bairro da barbearia', max_length=100)),
                ('cidade', models.CharField(help_text='Cidade da barbearia', max_length=100)),
                ('estado', models.CharField(help_text='Estado da barbearia (sigla Ex: PE, SP, RJ)', max_length=2)),
                ('localizacao', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Localização geográfica (lat/lng)', srid=4326)),
                ('telefone', models.CharField(blank=True, help_text='Telefone comercial da barbearia', max_length=15, null=True)),
                ('email', models.EmailField(help_text='Email comercial da barbearia', max_length=254)),
                ('ativo', models.BooleanField(db_index=True, default=True, help_text='Indica se a barbearia está ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp de atualização')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica se o registro foi soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp do delete', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_barbearias', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que deletou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_barbearias', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que atualizou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_barbearias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barbearia',
                'verbose_name_plural': 'Barbearias',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cnpj'], name='idx_barbearia_cnpj'), models.Index(fields=['ativo', 'is_deleted'], name='idx_barbearia_ativo'), models.Index(fields=['cidade', 'estado'], name='idx_barbearia_cidade_estado'), models.Index(fields=['created_at'], name='idx_barbearia_created_at'), models.Index(fields=['localizacao'], name='idx_barbearia_localizacao')],
            },
        ),
    ]
