# Generated by Django 5.1.4 on 2026-07-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbearia',
            name='balanceamento_minutos',
            field=models.IntegerField(default=60, help_text='Minutos antes do intervalo para encaixar agendamentos curtos (máx 60)'),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='buffer_minutos',
            field=models.IntegerField(default=0, help_text='Minutos de buffer entre agendamentos (tempo de limpeza/preparação)'),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='slot_padrao_minutos',
            field=models.IntegerField(default=30, help_text='Duração padrão do slot de agendamento em minutos'),
        ),
    ]
