# Generated by Django 5.1.4 on 2026-07-10 18:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comissao_percentual', models.IntegerField(help_text='Porcentagem retida pelo barbeiro (0 a 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ativo', models.BooleanField(default=True, help_text='Profissional ativo na equipe')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='tenants.barbearia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profissional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'db_table': 'core_profissional',
                'indexes': [models.Index(fields=['usuario'], name='idx_profissional_usuario'), models.Index(fields=['barbearia'], name='idx_profissional_barbearia')],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text="Nome legível (ex: 'Barba Terapia')", max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço nominal cobrado', max_digits=10)),
                ('duracao_minutos', models.IntegerField(default=30, help_text='Bloqueio de tempo na agenda')),
                ('ativo', models.BooleanField(default=True, help_text='Serviço disponível para agendamento')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='tenants.barbearia')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'core_servico',
                'indexes': [models.Index(fields=['barbearia'], name='idx_servico_barbearia')],
            },
        ),
    ]
