# Generated by Django 5.1.4 on 2026-07-14 15:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data/hora da última atualização')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comissao_percentual', models.IntegerField(help_text='Porcentagem retida pelo barbeiro (0 a 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ativo', models.BooleanField(default=True, help_text='Profissional ativo na equipe')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='tenants.barbearia')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que atualizou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_profissional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'db_table': 'core_profissional',
            },
        ),
        migrations.CreateModel(
            name='IntervaloIndisponivel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(help_text='Data do bloqueio')),
                ('hora_inicio', models.TimeField(help_text='Início do bloqueio')),
                ('hora_fim', models.TimeField(help_text='Término do bloqueio')),
                ('motivo', models.CharField(blank=True, help_text="Ex: 'Reunião', 'Compromisso pessoal'", max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervalos_indisponiveis_criados', to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalos_indisponiveis', to='operacional.profissional')),
            ],
            options={
                'verbose_name': 'Intervalo Indisponível',
                'verbose_name_plural': 'Intervalos Indisponíveis',
                'db_table': 'core_intervaloindisponivel',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='GradeHoraria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], help_text='0=Domingo, 6=Sábado')),
                ('hora_inicio', models.TimeField(help_text='Início da jornada (ex: 09:00)')),
                ('hora_fim', models.TimeField(help_text='Término da jornada (ex: 18:00)')),
                ('intervalo_inicio', models.TimeField(blank=True, help_text='Início do intervalo (ex: 12:00)', null=True)),
                ('intervalo_fim', models.TimeField(blank=True, help_text='Término do intervalo (ex: 13:00)', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Se False, o profissional não trabalha neste dia (folga)')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_horarias', to='operacional.profissional')),
            ],
            options={
                'verbose_name': 'Grade Horária',
                'verbose_name_plural': 'Grades Horárias',
                'db_table': 'core_gradehoraria',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='DiaIndisponivel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(help_text='Data específica de indisponibilidade')),
                ('motivo', models.CharField(blank=True, help_text="Ex: 'Férias', 'Folga pessoal', 'Compromisso'", max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dias_indisponiveis_criados', to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_indisponiveis', to='operacional.profissional')),
            ],
            options={
                'verbose_name': 'Dia Indisponível',
                'verbose_name_plural': 'Dias Indisponíveis',
                'db_table': 'core_diaindisponivel',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data/hora da última atualização')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text="Nome legível (ex: 'Barba Terapia')", max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço nominal cobrado', max_digits=10)),
                ('duracao_minutos', models.IntegerField(default=30, help_text='Bloqueio de tempo na agenda')),
                ('ativo', models.BooleanField(default=True, help_text='Serviço disponível para agendamento')),
                ('todos_profissionais_habilitados', models.BooleanField(default=True, help_text='Se SIM, todos os profissionais da barbearia podem realizar este serviço. Se NÃO, o DONO seleciona manualmente.')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='tenants.barbearia')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que atualizou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'core_servico',
            },
        ),
        migrations.CreateModel(
            name='ServicoProfissional',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('habilitado', models.BooleanField(default=True, help_text='Se False, o profissional não pode realizar este serviço')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_habilitados', to='operacional.profissional')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais_habilitados', to='operacional.servico')),
            ],
            options={
                'verbose_name': 'Habilitação de Serviço',
                'verbose_name_plural': 'Habilitações de Serviço',
                'db_table': 'core_servicoprofissional',
            },
        ),
        migrations.CreateModel(
            name='ConviteProfissional',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(help_text='Nome completo do barbeiro', max_length=255)),
                ('email', models.EmailField(help_text='Email para envio do convite', max_length=254)),
                ('cpf', models.CharField(help_text='CPF do barbeiro (apenas números)', max_length=11)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('comissao_percentual', models.IntegerField(help_text='Comissão oferecida (0-100)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito'), ('RECUSADO', 'Recusado'), ('EXPIRADO', 'Expirado')], default='PENDENTE', max_length=20)),
                ('token', models.CharField(help_text='Token único para aceitação', max_length=64, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField(help_text='Convite expira em 7 dias')),
                ('data_resposta', models.DateTimeField(blank=True, help_text='Quando o barbeiro aceitou/recusou', null=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_profissionais', to='tenants.barbearia')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_enviados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Convite Profissional',
                'verbose_name_plural': 'Convites Profissionais',
                'db_table': 'core_conviteprofissional',
                'indexes': [models.Index(fields=['barbearia', 'status'], name='idx_convite_barbearia_status'), models.Index(fields=['token'], name='idx_convite_token'), models.Index(fields=['email'], name='idx_convite_email')],
            },
        ),
        migrations.AddIndex(
            model_name='profissional',
            index=models.Index(fields=['usuario'], name='idx_profissional_usuario'),
        ),
        migrations.AddIndex(
            model_name='profissional',
            index=models.Index(fields=['barbearia'], name='idx_profissional_barbearia'),
        ),
        migrations.AlterUniqueTogether(
            name='profissional',
            unique_together={('usuario', 'barbearia')},
        ),
        migrations.AddIndex(
            model_name='intervaloindisponivel',
            index=models.Index(fields=['profissional', 'data'], name='idx_intervalo_prof_data'),
        ),
        migrations.AddIndex(
            model_name='gradehoraria',
            index=models.Index(fields=['profissional', 'ativo'], name='idx_grade_profissional_ativo'),
        ),
        migrations.AlterUniqueTogether(
            name='gradehoraria',
            unique_together={('profissional', 'dia_semana')},
        ),
        migrations.AlterUniqueTogether(
            name='diaindisponivel',
            unique_together={('profissional', 'data')},
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['barbearia'], name='idx_servico_barbearia'),
        ),
        migrations.AlterUniqueTogether(
            name='servicoprofissional',
            unique_together={('servico', 'profissional')},
        ),
    ]
