# Generated by Django 5.1.4 on 2026-07-11 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0002_freelancer_model_auditoria'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que atualizou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servico',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servico',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que atualizou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ConviteProfissional',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(help_text='Nome completo do barbeiro', max_length=255)),
                ('email', models.EmailField(help_text='Email para envio do convite', max_length=254)),
                ('cpf', models.CharField(help_text='CPF do barbeiro (apenas números)', max_length=11)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('comissao_percentual', models.IntegerField(help_text='Comissão oferecida (0-100)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito'), ('RECUSADO', 'Recusado'), ('EXPIRADO', 'Expirado')], default='PENDENTE', max_length=20)),
                ('token', models.CharField(help_text='Token único para aceitação', max_length=64, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField(help_text='Convite expira em 7 dias')),
                ('data_resposta', models.DateTimeField(blank=True, help_text='Quando o barbeiro aceitou/recusou', null=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_profissionais', to='tenants.barbearia')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_enviados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Convite Profissional',
                'verbose_name_plural': 'Convites Profissionais',
                'db_table': 'core_conviteprofissional',
                'indexes': [models.Index(fields=['barbearia', 'status'], name='idx_convite_barbearia_status'), models.Index(fields=['token'], name='idx_convite_token'), models.Index(fields=['email'], name='idx_convite_email')],
            },
        ),
    ]
