# Generated by Django 5.1.4 on 2026-07-11 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0003_alter_profissional_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='todos_profissionais_habilitados',
            field=models.BooleanField(default=True, help_text='Se SIM, todos os profissionais da barbearia podem realizar este serviço. Se NÃO, o DONO seleciona manualmente.'),
        ),
        migrations.CreateModel(
            name='DiaIndisponivel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(help_text='Data específica de indisponibilidade')),
                ('motivo', models.CharField(blank=True, help_text="Ex: 'Férias', 'Folga pessoal', 'Compromisso'", max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dias_indisponiveis_criados', to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_indisponiveis', to='operacional.profissional')),
            ],
            options={
                'verbose_name': 'Dia Indisponível',
                'verbose_name_plural': 'Dias Indisponíveis',
                'db_table': 'core_diaindisponivel',
                'ordering': ['data'],
                'unique_together': {('profissional', 'data')},
            },
        ),
        migrations.CreateModel(
            name='GradeHoraria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], help_text='0=Domingo, 6=Sábado')),
                ('hora_inicio', models.TimeField(help_text='Início da jornada (ex: 09:00)')),
                ('hora_fim', models.TimeField(help_text='Término da jornada (ex: 18:00)')),
                ('intervalo_inicio', models.TimeField(blank=True, help_text='Início do intervalo (ex: 12:00)', null=True)),
                ('intervalo_fim', models.TimeField(blank=True, help_text='Término do intervalo (ex: 13:00)', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Se False, o profissional não trabalha neste dia (folga)')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_horarias', to='operacional.profissional')),
            ],
            options={
                'verbose_name': 'Grade Horária',
                'verbose_name_plural': 'Grades Horárias',
                'db_table': 'core_gradehoraria',
                'ordering': ['dia_semana'],
                'indexes': [models.Index(fields=['profissional', 'ativo'], name='idx_grade_profissional_ativo')],
                'unique_together': {('profissional', 'dia_semana')},
            },
        ),
        migrations.CreateModel(
            name='IntervaloIndisponivel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(help_text='Data do bloqueio')),
                ('hora_inicio', models.TimeField(help_text='Início do bloqueio')),
                ('hora_fim', models.TimeField(help_text='Término do bloqueio')),
                ('motivo', models.CharField(blank=True, help_text="Ex: 'Reunião', 'Compromisso pessoal'", max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervalos_indisponiveis_criados', to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalos_indisponiveis', to='operacional.profissional')),
            ],
            options={
                'verbose_name': 'Intervalo Indisponível',
                'verbose_name_plural': 'Intervalos Indisponíveis',
                'db_table': 'core_intervaloindisponivel',
                'ordering': ['data', 'hora_inicio'],
                'indexes': [models.Index(fields=['profissional', 'data'], name='idx_intervalo_prof_data')],
            },
        ),
        migrations.CreateModel(
            name='ServicoProfissional',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('habilitado', models.BooleanField(default=True, help_text='Se False, o profissional não pode realizar este serviço')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_habilitados', to='operacional.profissional')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais_habilitados', to='operacional.servico')),
            ],
            options={
                'verbose_name': 'Habilitação de Serviço',
                'verbose_name_plural': 'Habilitações de Serviço',
                'db_table': 'core_servicoprofissional',
                'unique_together': {('servico', 'profissional')},
            },
        ),
    ]
